name: presentation demo
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: access to the repository
        uses: actions/checkout@v3
      - name: install dart
        uses: dart-lang/setup-dart@v1

      # - run: dart run test1.dart
